GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('digestion_tank')
        .category('haruk0')
        .setMaxIOSize(3, 3, 3, 3)
        .setEUIO('in')
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.CHEMICAL)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('digestion_tank', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('digestion_tank')
        .appearanceBlock(GTBlocks.CASING_STEEL_SOLID)
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('#F#F#', '#CCC#', '#HHH#', '#HHH#', '#HHH#', '#CCC#', '#HHH#', '#HHH#', '#HHH#', '#CCC#')
            .aisle('F###F', 'CHHHC', 'H###H', 'H###H', 'H###H', 'C###C', 'H###H', 'H###H', 'H###H', 'CHHHC')
            .aisle('#####', 'CHHHC', 'H#P#H', 'H#P#H', 'H#P#H', 'C#P#C', 'H#P#H', 'H#P#H', 'H#P#H', 'CHHHC')
            .aisle('F###F', 'CHHHC', 'H###H', 'H###H', 'H###H', 'C###C', 'H###H', 'H###H', 'H###H', 'CHHHC')
            .aisle('#F#F#', '#CCC#', '#HHH#', '#HKH#', '#HHH#', '#CCC#', '#HHH#', '#HHH#', '#HHH#', '#CCC#')
        .where('#', Predicates.any())
        .where('F', Predicates.blocks('gtceu:steel_frame'))
        .where('C', Predicates.blocks('gtceu:steel_machine_casing')
            .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
        .where('H', Predicates.blocks('gtceu:solid_machine_casing').setMinGlobalLimited(80)
            .or(Predicates.autoAbilities(definition.getRecipeTypes())))
        .where('P', Predicates.blocks('gtceu:steel_pipe_casing'))
        .where('K', Predicates.controller(Predicates.blocks(definition.get())))
        .build())
.workableCasingModel('gtceu:block/casings/solid/machine_casing_solid_steel', 'gtceu:block/multiblock/large_chemical_reactor')
})