const $SteamToaster = Java.loadClass('com.gregtechceu.gtceu.common.machine.multiblock.steam.SteamParallelMultiblockMachine')

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('large_steam_toaster_oven', 'multiblock')
        .machine((holder) => new $SteamToaster(holder, 2))
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('steam_toaster_oven')
        .recipeModifier((machine, recipe) => $SteamToaster.recipeModifier(machine, recipe), true)
        .pattern(definition => FactoryBlockPattern.start()
        .aisle("DDD", "#C#", "#C#")
        .aisle("DDD", "C#C", "CCC")
        .aisle("DDD", "#H#", "#C#")
   .where('#', Predicates.any())
   .where('C', Predicates.blocks('gtceu:steam_machine_casing')
        .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.STEAM).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS).setMaxGlobalLimited(1)))
   .where("D", Predicates.blocks("gtceu:bronze_firebox_casing"))
   .where('H', Predicates.controller(Predicates.blocks(definition.get())))
        .build())
    .workableCasingModel("gtceu:block/casings/solid/machine_casing_bronze_plated_bricks", "gtceu:block/machines/electric_oven")
  })