const $SteamVaccum = Java.loadClass('com.gregtechceu.gtceu.common.machine.multiblock.steam.SteamParallelMultiblockMachine')

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('large_steam_vaccum_chamber', 'multiblock')
        .machine((holder) => new $SteamVaccum(holder, 2))
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('steam_vaccum_chamber')
        .recipeModifier((machine, recipe) => $SteamVaccum.recipeModifier(machine, recipe), true)
        .pattern(definition => FactoryBlockPattern.start()
        .aisle("CCC", "CEC", "CEC", "CCC")
        .aisle("CDC", "E#E", "E#E", "CDC")
        .aisle("CHC", "CEC", "CEC", "CCC")
   .where('#', Predicates.any())
   .where('C', Predicates.blocks('gtceu:steam_machine_casing')
        .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.STEAM).setMaxGlobalLimited(1))
        .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS).setMaxGlobalLimited(1)))
   .where("D", Predicates.blocks("gtceu:bronze_pipe_casing"))
   .where("E", Predicates.blocks('create:framed_glass'))
   .where('H', Predicates.controller(Predicates.blocks(definition.get())))
        .build())
    .workableCasingModel("gtceu:block/casings/solid/machine_casing_bronze_plated_bricks", "gtceu:block/machines/air_scrubber")
  })