priority: 300

ServerEvents.recipes(event => {

//TYPE
event.remove({ type: 'minecraft:blasting'})
event.remove({ type: 'bloodmagic:arcfurnace'})
event.remove({ type: 'twilightforest:uncrafting'})
event.remove({ type: 'twilightforest:uncrafting_table'})
event.remove({ type: 'productivebees:advanced_beehive'})
event.remove({ type: 'ad_astra:alloying'})
event.remove({ type: 'nuclearcraft:nuclear_furnace'})


//ID
event.remove({ id: 'tconstruct:common/basalt_blast_furnace'})
event.remove({ id: 'jei:/tconstruct/smeltery/melting/metal/iron/ingot_5'})
event.remove({ id: 'minecraft:packed_mud' })
event.remove({ id: 'minecraft:mud_bricks' })
event.remove({ id: 'gtceu:smelting/smelt_dust_mud_mixture_to_ingot' })
event.remove({ id: 'gtceu:smelting/coke_oven_brick' })
event.remove({ id: 'gtceu:alloy_smelter/coke_oven_brick' })
event.remove({ id: 'gtceu:smelting/brick_from_compressed_clay' })
event.remove({ id: 'gtceu:alloy_smelter/form_brick' })
event.remove({ id: 'gtceu:smelting/smelt_dust_charred_mud_to_ingot' })
event.remove({ id: 'gtceu:smelting/smelt_dust_bronze_to_ingot'})
event.remove({ id: 'forestry:ingot_bronze_alloying'})
event.remove({ id: 'gtceu:shaped/steam_pressurizer' })
event.remove({ id: 'gtceu:steam_pressurizer/hp_steam' })
event.remove({ id: 'twilightforest:uncrafting_table' })
event.remove({ id: 'gtceu:shapeless/compressed_clay' })
event.remove({ id: 'gtceu:shaped/processing_array' })
event.remove({ id: 'create:crafting/materials/andesite_alloy_from_zinc' })
event.remove({ id: 'create:crafting/materials/andesite_alloy' })
event.remove({ id: 'gtceu:shaped/pyrolyse_oven' })
event.remove({ id: 'gtceu:shaped_fluid_container/treated_wood_planks' })
event.remove({ id: 'gtceu:shapeless/dust_bronze' })
event.remove({ id: 'create:crafting/kinetics/whisk' })
event.remove({ id: 'create:crafting/kinetics/shaft' })
event.remove({ id: 'create:crafting/kinetics/cogwheel' })
event.remove({ id: 'create:crafting/kinetics/large_cogwheel' })
event.remove({ id: 'create:deploying/cogwhell' })
event.remove({ id: 'create:crafting/kinetics/large_cogwheel_from_little' })
event.remove({ id: 'create:deploying/large_cogwhell' })
event.remove({ id: 'create:crafting/kinetics/water_wheel' })
event.remove({ id: 'create:crafting/kinetics/large_water_wheel' })
event.remove({ id: 'create:crafting/kinetics/windmill_bearing' })
event.remove({ id: 'create:crafting/kinetics/steam_engine' })
event.remove({ id: 'create:crafting/kinetics/mechanical_bearing' })
event.remove({ id: 'create:crafting/kinetics/fluid_tank' })
event.remove({ id: 'create:crafting/kinetics/item_vault' })
event.remove({ id: 'create:crafting/kinetics/white_sail' })
event.remove({ id: 'notreepunching:campfire/brick' })
event.remove({ id: 'notreepunching:clay_brick_from_blocks' })
event.remove({ id: 'notreepunching:clay_brick_from_balls' })
event.remove({ id: 'gtmthings:assembler/hv_digital_miner' })
event.remove({ id: 'gtmthings:assembler/mv_digital_miner' })
event.remove({ id: 'gtmthings:assembler/lv_digital_miner' })


//SALIDA
event.remove({ output: 'create:encased_fan' })
event.remove({ output: 'create:andesite_alloy' })
event.remove({ output: 'ad_astra:etrionic_blast_furnace' })
event.remove({ output: 'productivebees:gene_indexer' })
event.remove({ output: 'productivebees:bottler' })
event.remove({ output: 'productivebees:centrifuge' })
event.remove({ output: 'productivebees:powered_centrifuge' })
event.remove({ output: 'productivebees:heated_centrifuge' })
event.remove({ output: 'productivebees:breeding_chamber' })
event.remove({ output: 'productivebees:incubator' })
event.remove({ output: 'productivebees:bee_cage' })
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:sphalerite"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:palladium"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:lepidolite"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:sheldonite"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:bastnasite"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:tetrahedrite"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:neodymium"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:oilsands"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:pyrolusite"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:scheelite"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:stibnite"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:chromite"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:electrotine"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:vanadium_magnetite"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:barite"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:tantalite"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:naquadah"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:ilmenite"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:pyrochlore"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:molybdenum"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:tricalcium_phosphate"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:tungstate"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:graphite"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:galena"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:bauxite"}}').weakNBT()})
event.remove({ output: Item.of('productivebees:spawn_egg_configurable_bee', '{EntityTag:{type:"productivebees:cobaltite"}}').weakNBT()})

//MOD
event.remove({ mod: 'laserio' })
event.remove({ mod: 'megacells' })
event.remove({ mod: 'buildinggadgets2' })
event.remove({ mod: 'toms_storage' })
event.remove({ mod: 'hostilenetworks' })
event.remove({ mod: 'nuclearcraft' })
//event.remove({ mod: 'productivebees' })


//CONDITIONS


})

