ServerEvents.recipes(event => {
    
    // OAK TREE //
    event.recipes.gtceu.arboreal_manufacter('am_oak_log')
        .chancedInput('4x minecraft:oak_sapling', 1500, 0)
        .perTick(true)
        .inputFluids(Fluid.of("minecraft:water", 2))
        .inputFluids(Fluid.of("gtceu:steam", 64))
        .perTick(false)
        .itemOutputs('64x minecraft:oak_log', '2x minecraft:oak_sapling', '4x minecraft:apple')
        .duration(2400)
    
    event.recipes.gtceu.arboreal_manufacter('am_oak_log_boost')
        .chancedInput('8x minecraft:oak_sapling', 1500, 0)
        .itemInputs('4x minecraft:bone_meal')
        .perTick(true)
        .inputFluids(Fluid.of("minecraft:water", 4))
        .inputFluids(Fluid.of("gtceu:steam", 92))
        .perTick(false)
        .itemOutputs('192x minecraft:oak_log', '4x minecraft:oak_sapling', '8x minecraft:apple')
        .duration(4000)

        // SPRUCE TREE //
    event.recipes.gtceu.arboreal_manufacter('am_spruce_log')
        .chancedInput('4x minecraft:spruce_sapling', 1500, 0)
        .perTick(true)
        .inputFluids(Fluid.of("minecraft:water", 2))
        .inputFluids(Fluid.of("gtceu:steam", 64))
        .perTick(false)
        .itemOutputs('64x minecraft:spruce_log', '2x minecraft:spruce_sapling')
        .duration(2400)
    
    event.recipes.gtceu.arboreal_manufacter('am_spruce_log_boost')
        .chancedInput('8x minecraft:spruce_sapling', 1500, 0)
        .itemInputs('4x minecraft:bone_meal')
        .perTick(true)
        .inputFluids(Fluid.of("minecraft:water", 4))
        .inputFluids(Fluid.of("gtceu:steam", 92))
        .perTick(false)
        .itemOutputs('192x minecraft:spruce_log', '4x minecraft:spruce_sapling')
        .duration(4000)

        // RUBBER TREE
    event.recipes.gtceu.arboreal_manufacter('am_rubber_log')
        .chancedInput('4x gtceu:rubber_sapling', 1500, 0)
        .perTick(true)
        .inputFluids(Fluid.of("minecraft:water", 2))
        .inputFluids(Fluid.of("gtceu:steam", 64))
        .perTick(false)
        .itemOutputs('24x gtceu:rubber_log', '2x gtceu:rubber_sapling')
        .chancedOutput('4x gtceu:sticky_resin', 1000, 0)
        .duration(2400)
    
    event.recipes.gtceu.arboreal_manufacter('am_rubber_log_boost')
        .chancedInput('8x gtceu:rubber_sapling', 1500, 0)
        .itemInputs('4x minecraft:bone_meal')
        .perTick(true)
        .inputFluids(Fluid.of("minecraft:water", 4))
        .inputFluids(Fluid.of("gtceu:steam", 92))
        .perTick(false)
        .itemOutputs('48x gtceu:rubber_log', '4x gtceu:rubber_sapling')
        .chancedOutput('8x gtceu:sticky_resin', 1000, 0)
        .duration(4000)

        // CHERRY TREE //
    event.recipes.gtceu.arboreal_manufacter('am_cherry_log')
        .chancedInput('4x minecraft:cherry_sapling', 1500, 0)
        .perTick(true)
        .inputFluids(Fluid.of("minecraft:water", 2))
        .inputFluids(Fluid.of("gtceu:steam", 64))
        .perTick(false)
        .itemOutputs('64x minecraft:cherry_log', '2x minecraft:cherry_sapling')
        .duration(2400)
    
    event.recipes.gtceu.arboreal_manufacter('am_cherry_log_boost')
        .chancedInput('8x minecraft:cherry_sapling', 1500, 0)
        .itemInputs('4x minecraft:bone_meal')
        .perTick(true)
        .inputFluids(Fluid.of("minecraft:water", 4))
        .inputFluids(Fluid.of("gtceu:steam", 92))
        .perTick(false)
        .itemOutputs('192x minecraft:cherry_log', '4x minecraft:cherry_sapling')
        .duration(4000)


})