GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('arboreal_manufacter')
        .category('haruk0')
        .setMaxIOSize(4, 6, 3, 3)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.MINER)
})

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('arboreal_manufacter', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('arboreal_manufacter')
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("CCCCC", "VCCCV", "VEEEV", "VEEEV", "VEEEV", "CCCCC")
            .aisle("CFGFC", "C###C", "E###E", "E#T#E", "E###E", "CEEEC")
            .aisle("CGFGC", "C#R#C", "E#R#E", "ETRTE", "E#T#E", "CEEEC")
            .aisle("CFGFC", "C###C", "E###E", "E#T#E", "E###E", "CEEEC")
            .aisle("CCHCC", "VEEEV", "VEEEV", "VEEEV", "VEEEV", "CCCCC")
            .where('#', Predicates.any())
            .where('V', Predicates.blocks('gtceu:invar_frame'))
            .where('C', Predicates.blocks('gtceu:steam_machine_casing')
                .or(Predicates.abilities(PartAbility.STEAM_EXPORT_ITEMS).setMaxGlobalLimited(1))
                .or(Predicates.abilities(PartAbility.STEAM_IMPORT_ITEMS).setMaxGlobalLimited(2))
                .or(Predicates.autoAbilities(definition.getRecipeTypes())))
            .where("E", Predicates.blocks("create:framed_glass"))
            .where("R", Predicates.blocks("minecraft:oak_log"))
            .where("T", Predicates.blocks("minecraft:oak_leaves"))
            .where("F", Predicates.blocks("minecraft:packed_mud"))
            .where("G", Predicates.blocks("minecraft:moss_block"))
            .where('H', Predicates.controller(Predicates.blocks(definition.get())))
            .build())
    .workableCasingRenderer("gtceu:block/casings/solid/machine_casing_bronze_plated_bricks", "gtceu:block/multiblock/bedrock_ore_miner", true)
  })